apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-spring-api.fullname" . }}
  labels:
{{ include "java-spring-api.labels" . | nindent 4 }}
data:
  application.properties: {{ toYaml .Values.applicationProperties | nindent 4 }}
