apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "java-spring-api.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /{{ or $.Values.ingress.path  $.Release.Name }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "java-spring-api.fullname" $ }}
                port:
                  number: 8080
