apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-spring-api.fullname" . }}
  labels:
{{ include "java-spring-api.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "java-spring-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: web
      port: 8080
    - name: actuator
      port: 8081
